/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_JniMain */

#ifndef _Included_com_jni_JniMain
#define _Included_com_jni_JniMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_JniMain
 * Method:    c_constructCore
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jni_JniMain_c_1constructCore
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_JniMain
 * Method:    c_process
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_jni_JniMain_c_1process
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_jni_JniMain
 * Method:    c_destroyCore
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jni_JniMain_c_1destroyCore
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
